name: jaffle_shop
description: ''
version: v11
author: null
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/job_airflow_redshift:
    name: job_airflow_redshift
    description: ''
    fabricUID: 5646
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-08-22 10:43:20'
    author: jrohit+e2e@prophecy.io
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2023-08-14 06:59:40'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/stg_orders:
    name: stg_orders
    schema: null
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - models/staging/stg_orders.sql
    - .prophecy/ide/models/stg_orders.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2023-08-14 06:59:40'
  .prophecy/metadata/sqlmodels/orders:
    name: orders
    schema: null
    description: This table has basic information about orders, as well as some derived
      facts based on payments
    author: jrohit+e2e@prophecy.io
    files:
    - models/orders.sql
    - .prophecy/ide/models/orders.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2023-08-14 06:59:40'
  .prophecy/metadata/sqlmodels/customers:
    name: customers
    schema: null
    description: This table has basic information about a customer, as well as some
      derived facts based on a customer's orders
    author: jrohit+e2e@prophecy.io
    files:
    - models/customers.sql
    - .prophecy/ide/models/customers.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2023-08-14 06:59:40'
  .prophecy/metadata/sqlmodels/stg_payments:
    name: stg_payments
    schema: null
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - models/staging/stg_payments.sql
    - .prophecy/ide/models/stg_payments.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2023-08-14 06:59:40'
  .prophecy/metadata/sqlmodels/newmodel:
    name: newmodel
    schema: null
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - models/newmodel.sql
    - .prophecy/ide/models/newmodel.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2023-08-21 11:44:27'
  .prophecy/metadata/sqlmodels/customModel:
    name: customModel
    schema: null
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - models/customModel.sql
    - .prophecy/ide/models/customModel.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2023-08-14 11:01:50'
  .prophecy/metadata/sqlmodels/stg_customers:
    name: stg_customers
    schema: null
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - models/staging/stg_customers.sql
    - .prophecy/ide/models/stg_customers.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2023-08-14 06:59:40'
sqlSnapshots: {}
sqlTests: {}
sqlMacros:
  .prophecy/metadata/sqlmacros/generic_round:
    name: generic_round
    macroType: expression
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - macros/generic_round.sql
    - .prophecy/ide/macros/generic_round.json
    createdAt: '2023-08-22 10:23:22'
  .prophecy/metadata/sqlmacros/select_distinct_columns:
    name: select_distinct_columns
    macroType: query
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - macros/select_distinct_columns.sql
    - .prophecy/ide/macros/select_distinct_columns.json
    - macros/macros.yml
    createdAt: '2023-08-22 10:25:01'
sqlSeeds:
  .prophecy/metadata/sqlseeds/ramdomseed:
    name: ramdomseed
    schema:
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - seeds/ramdomseed.csv
    createdAt: '2023-08-21 06:55:19'
  .prophecy/metadata/sqlseeds/raw_customers:
    name: raw_customers
    schema:
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - seeds/raw_customers.csv
    createdAt: '2023-08-14 06:59:40'
  .prophecy/metadata/sqlseeds/raw_orders:
    name: raw_orders
    schema:
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: user_id
        dataType:
          type: Integer
      - name: order_date
        dataType:
          type: Date
      - name: status
        dataType:
          type: String
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - seeds/raw_orders.csv
    createdAt: '2023-08-14 06:59:40'
  .prophecy/metadata/sqlseeds/raw_payments:
    name: raw_payments
    schema:
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: order_id
        dataType:
          type: Integer
      - name: payment_method
        dataType:
          type: String
      - name: amount
        dataType:
          type: Integer
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - seeds/raw_payments.csv
    createdAt: '2023-08-14 06:59:40'
sqlSources:
  .prophecy/metadata/sqlsources/dev_public:
    name: dev.public
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2023-08-14 11:02:09'
    tables:
    - name: customers
      schema:
        providerType: databricks
        fields: []
      description: null
      author: jrohit+e2e@prophecy.io
      createdAt: '2023-08-14 11:02:09'
    - name: listing
      schema:
        providerType: databricks
        fields: []
      description: null
      author: jrohit+e2e@prophecy.io
      createdAt: '2023-08-14 11:08:51'
  .prophecy/metadata/sqlsources/sample_data_dev_tickit:
    name: sample_data_dev.tickit
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2023-08-14 11:09:19'
    tables:
    - name: listing
      schema:
        providerType: databricks
        fields: []
      description: This dataset is a comprehensive representation of the listings
        available on the platform, including the seller ID, event ID, date ID, number
        of tickets, price per ticket, total price, and listing time. This data is
        useful for analyzing the platform's performance, identifying popular events,
        and monitoring ticket prices. It is also useful for developing marketing strategies
        and making data-driven decisions.
      author: jrohit+e2e@prophecy.io
      createdAt: '2023-08-14 11:09:19'
  .prophecy/metadata/sqlsources/sample_data_dev_tpch:
    name: sample_data_dev.tpch
    description: null
    author: jrohit+e2e@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2023-08-14 11:02:43'
    tables:
    - name: customer
      schema:
        providerType: databricks
        fields: []
      description: null
      author: jrohit+e2e@prophecy.io
      createdAt: '2023-08-14 11:02:43'
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: jrohit+e2e@prophecy.io
  createdAt: '2023-08-14 06:59:40'
dependencies: '[]'
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
