---
version: 2
sources:
- name: "dev.jsr"
  database: "dev"
  schema: "jsr"
  config:
    enabled: true
  tables:
  - name: "customers"
    columns:
    - name: "customer_id"
      dataType:
        type: "Integer"
    - name: "first_name"
      dataType:
        type: "String"
    - name: "last_name"
      dataType:
        type: "String"
    - name: "first_order"
      dataType:
        type: "Date"
    - name: "most_recent_order"
      dataType:
        type: "Date"
    - name: "number_of_orders"
      dataType:
        type: "Bigint"
    - name: "customer_lifetime_value"
      dataType:
        type: "Bigint"
- name: "dev.public"
  database: "dev"
  schema: "public"
  config:
    enabled: true
  tables:
  - name: "customers"
    columns:
    - name: "customer_id"
      dataType:
        type: "Integer"
    - name: "first_name"
      dataType:
        type: "String"
    - name: "last_name"
      dataType:
        type: "String"
    - name: "first_order"
      dataType:
        type: "Date"
    - name: "most_recent_order"
      dataType:
        type: "Date"
    - name: "number_of_orders"
      dataType:
        type: "Bigint"
    - name: "customer_lifetime_value"
      dataType:
        type: "Bigint"
- name: "sample_data_dev.tpcds"
  database: "sample_data_dev"
  schema: "tpcds"
  config:
    enabled: true
  tables:
  - name: "customer"
    columns:
    - name: "c_customer_sk"
      dataType:
        type: "Integer"
    - name: "c_customer_id"
      dataType:
        type: "Char"
    - name: "c_current_cdemo_sk"
      dataType:
        type: "Integer"
    - name: "c_current_hdemo_sk"
      dataType:
        type: "Integer"
    - name: "c_current_addr_sk"
      dataType:
        type: "Integer"
    - name: "c_first_shipto_date_sk"
      dataType:
        type: "Integer"
    - name: "c_first_sales_date_sk"
      dataType:
        type: "Integer"
    - name: "c_salutation"
      dataType:
        type: "Char"
    - name: "c_first_name"
      dataType:
        type: "Char"
    - name: "c_last_name"
      dataType:
        type: "Char"
    - name: "c_preferred_cust_flag"
      dataType:
        type: "Char"
    - name: "c_birth_day"
      dataType:
        type: "Integer"
    - name: "c_birth_month"
      dataType:
        type: "Integer"
    - name: "c_birth_year"
      dataType:
        type: "Integer"
    - name: "c_birth_country"
      dataType:
        type: "String"
    - name: "c_login"
      dataType:
        type: "Char"
    - name: "c_email_address"
      dataType:
        type: "Char"
    - name: "c_last_review_date_sk"
      dataType:
        type: "Integer"
